window.switStrings =	{
	"STR_LOADING_PRELOAD_FONT_2": "0",
	"STR_LOADING_PRELOAD_FONT_1": "0",
	"STR_LOADING_PERCENT": "LOADING...",
	"STR_RESET_TITLE": "NEW GAME",
	"STR_RESET_INFO": "Delete progress?",
	"STR_QUIT_TITLE": "QUIT GAME",
	"STR_QUIT_INFO": "Are you sure?",
	"STR_PAUSE_TITLE": "PAUSE",
	"STR_COUNTER_GO": "GO!",
	"STR_HUD_LIFE_NUMBER": "#",
	"STR_HUD_COUNTER_NUMBER": "#",
	"STR_ENDLEVEL_SUBTITLE2": "RUSH TIME",
	"STR_ENDLEVEL_TITLE01": "GREAT!",
	"STR_ENDLEVEL_TITLE02": "ROYAL!",
	"STR_ENDLEVEL_TITLE03": "WICKED!",
	"STR_ENDLEVEL_TREASURES_NAME_MAL": "SPRAYPAINT CANS",
	"STR_ENDLEVEL_TREASURES_NAME_UMA": "MAGIC SEASHELLS",
	"STR_ENDLEVEL_TREASURES_NUMBER": "#",
	"STR_ENDLEVEL_ADRENALINE_NAME": "RUSH TIME",
	"STR_ENDLEVEL_GOAL_NUMBER": "#",
	"STR_ENDLEVEL_GOAL_NAME": "GOAL TIME",
	"STR_ENDLEVEL_YOURTIME_NAME": "YOUR TIME",
	"STR_ENDLEVEL_YOURTIME_NUMBER": "#",
	"STR_SELECTCHARACTER_TITLE": "CHOOSE YOUR STORY!",
	"STR_SELECTCHARACTER_UMA": "UMA",
	"STR_SELECTCHARACTER_MAL": "MAL",
	"STR_HELP_INFO01": "Tap to jump",
	"STR_HELP_INFO01PC": "Press Z to jump",
	"STR_HELP_INFO02": "Swipe to attack",
	"STR_HELP_INFO02PC": "Press X to attack",
	"STR_HELP_INFO03": "Hop on enemies and objects",
	"STR_HELP_INFO04": "Jump off poles and other items to fill your Rush Meter.",
	"STR_HELP_INFO05": "Fill your Rush Meter to go farther, faster and collect special items.",
	"STR_HELP_BONUS_INFO01": "Tap to dodge",
	"STR_HELP_BONUS_INFO01PC": "Press Z to dodge ",
	"STR_HELP_BONUS_INFO02": "Swipe to attack",
	"STR_HELP_BONUS_INFO02PC": "Press X to attack",
	"STR_HELP_NUMBER01": "1",
	"STR_HELP_NUMBER02": "2",
	"STR_HELP_NUMBER03": "3",
	"STR_HELP_NUMBER04": "4",
	"STR_HELP_NUMBER05": "5",
	"STR_TRYAGAIN_SUBTITLE": "We won't give up so easily!",
	"STR_TRYAGAIN_TITLE": "LET'S TRY AGAIN",
	"STR_TROPHY_TITLE": "ACHIEVEMENTS",
	"STR_TROPHY_NAME01": "Ways to be wicked",
	"STR_TROPHY_NAME02": "Poor unfortunate souls",
	"STR_TROPHY_NAME03": "Rotten to the core",
	"STR_TROPHY_NAME04": "Necessary evil",
	"STR_TROPHY_NAME05": "Two sides of the story",
	"STR_TROPHY_NAME06": "Let’s set it off",
	"STR_TROPHY_INFO01": "Collect # spraypaint cans",
	"STR_TROPHY_INFO02": "Collect # seashells",
	"STR_TROPHY_INFO03": "Defeat # enemies",
	"STR_TROPHY_INFO04": "Finish the bonus levels",
	"STR_TROPHY_INFO05": "Finish both story campaigns",
	"STR_TROPHY_INFO06": "Get to Rush Mode in every level ",
	"STR_METAMAP_LEVEL01": "AURADON PREP",
	"STR_METAMAP_LEVEL02": "ISLE OF THE LOST",
	"STR_METAMAP_LEVEL03": "UMA’S SHIP",
	"STR_METAMAP_LEVEL04": "ETERNAL LOVE BOAT",
	"STR_METAMAP_LEVEL05": "OPEN SEA",
	"STR_DIALOG_NAME_MAL": "Mal",
	"STR_DIALOG_NAME_UMA": "Uma",
	"STR_DIALOG_NAME_BEN": "Ben",
	"STR_DIALOG_NAME_EVIE": "Evie",
	"STR_DIALOG_NAME_CARLOS": "Carlos",
	"STR_DIALOG_NAME_JAY": "Jay",
	"STR_DIALOG_NAME_GIL": "Gil",
	"STR_DIALOG_NAME_HARRY": "Harry",
	"STR_DIALOG_NAME_HARRY_GIL": "Harry & Gil",
	"STR_DIALOG_NAME_MAL_BEN_UMA": "Mal, Ben & Uma",
	"STR_INTRO_MAL_01_01": "Take back this moment that has past, return it… reverse it?",
	"STR_INTRO_MAL_01_02": "Wait… are you trying to spell me right now? Why would you trick me? \nI thought we were in this together, Mal!",
	"STR_INTRO_MAL_01_03": "I tried... but I’m not a perfect princess! I’m not a lady of the court…\nI'm a VK. That's what I've always been. I’m sorry, Ben…",
	"STR_OUTRO_MAL_01_01": "Don’t you miss life back on the Isle of the Lost?",
	"STR_OUTRO_MAL_01_02": "Seriously, Mal? Miss the Isle? There’s nothing back there for us... \nBesides, Auradon is great! This is our home. This is who we are now!",
	"STR_INTRO_MAL_02_01": "Hey Mal, why in such a hurry?",
	"STR_INTRO_MAL_02_02": "Oh… um… don’t worry about me, Carlos. \nIt’s nothing, everything's fine…",
	"STR_INTRO_MAL_02_03": "Mal! Just saw the new scooter Ben got you. Sweet ride! \nLooks like you got that royal pretty-boy wrapped around your pinky!",
	"STR_INTRO_MAL_02_04": "Oh, the scooter? Well that's just… \nWait… that gives me an idea…",
	"STR_OUTRO_MAL_02_01": "I just… don’t belong here anymore. Maybe I never did... \nNoble steed proud and fair, you shall take me anywhere…",
	"STR_INTRO_MAL_03_01": "Well, well, well... what a surprise, just wait until Uma hears you’re back. \nShe’s never gonna give you back your old territory…",
	"STR_INTRO_MAL_03_02": "Oh, that’s fine. Because I’ll be TAKING it!",
	"STR_OUTRO_MAL_03_01": "What are you doing here?",
	"STR_OUTRO_MAL_03_02": "Mal, I’m so sorry about our fight. It was my fault!",
	"STR_OUTRO_MAL_03_03": "No… it’s not your fault. Not at all! It’s me… I don’t fit in, Ben. I’m sorry. \nI really gave it my best shot. Please… just go. I’m sorry…",
	"STR_INTRO_MAL_04_01": "Guys, where’s Ben?",
	"STR_INTRO_MAL_04_02": "Looking for your wee prince? If you want to see that royal baby-face ever again, tell Mal she’d better come to the chop shop tonight… alone!",
	"STR_INTRO_MAL_04_03": "This fight is between Uma and me!",
	"STR_OUTRO_MAL_04_01": "Ha! Just because you’re a pretty little Auradon girl doesn’t mean you always get to win! Now... if you want to see your beast boy again, bring me Fairy Godmother’s wand tomorrow at noon!",
	"STR_INTRO_MAL_05_01": "Give me the wand!",
	"STR_INTRO_MAL_05_02": "Give me Ben!",
	"STR_INTRO_MAL_05_03": "There you have it.",
	"STR_INTRO_MAL_05_04": "Cut him loose!\nBy the power of the sea, tear it down and set us free…",
	"STR_INTRO_MAL_05_05": "No! The wand… it's a fake! \nYou don’t get to win every time! Get ‘em!",
	"STR_OUTRO_MAL_06_01": "Come on, come on, this way!",
	"STR_OUTRO_MAL_06_02": "Oh no! I dropped my spell book!",
	"STR_OUTRO_MAL_06_03": "Leave it, Mal! We need to go now!!!",
	"STR_INTRO_MAL_07_01": "I wish I had time to explain.",
	"STR_INTRO_MAL_07_02": "I have an announcement: \nUma will be joining the court as my lady.",
	"STR_INTRO_MAL_07_03": "So as my gift to her I’m bringing down the barrier between Auradon and the Isle of the Lost once and for all.",
	"STR_INTRO_MAL_07_04": "Listen to your king!",
	"STR_INTRO_MAL_07_05": "Ben? What is this? Something is not right…",
	"STR_OUTRO_MAL_07_01": "Ben did that for me?",
	"STR_INTRO_MAL_08_01": "Ben’s been spelled. \nUma must have found my spell book when we left the Isle!",
	"STR_INTRO_MAL_BOSS_01": "I know who I am. I’m part Isle and part Auradon. I can’t change that. \nBen… you know me... and you’ve always known who we were and who we can be!",
	"STR_INTRO_MAL_BOSS_02": "……………………..",
	"STR_INTRO_MAL_BOSS_03": "Don’t listen to her!",
	"STR_OUTRO_MAL_BOSS_01": "Ben, I know what love is. Of course I love you! I’ve always loved you…",
	"STR_INTRO_UMA_06_01": "How does it feel being a king now, eh?",
	"STR_INTRO_UMA_06_02": "Give it a rest Harry, we don’t want damaged goods.\nYou better hope your girlfriend comes through, pretty boy…",
	"STR_INTRO_UMA_06_03": "She’s not my girlfriend anymore. And anyways, I’m sorry… \nI get that you didn't deserve to be left behind on the Isle…",
	"STR_INTRO_UMA_06_04": "Don’t pretend to look out for me, Prince Charming. No one is, no one has. Ever.",
	"STR_OUTRO_UMA_06_01": "When you brought Evie, Carlos, Jay and Mal to Auradon... that was the angriest I’ve ever been. What makes them special? \nWhy did you forget about us?",
	"STR_OUTRO_UMA_06_02": "You’re right, Uma. This is all my fault. But you’re a leader Uma, you can help me fix this. Come to Auradon and become part of the solution!",
	"STR_OUTRO_UMA_06_03": "Part of the solution? Nah, I don’t need you, I can get that on my own.",
	"STR_OUTRO_UMA_06_04": "Hey guys, they’re here!",
	"STR_INTRO_UMA_05_01": "Give me the wand!",
	"STR_INTRO_UMA_05_02": "Give me Ben!",
	"STR_INTRO_UMA_05_03": "There you have it.",
	"STR_INTRO_UMA_05_04": "Cut him loose!\nBy the power of the sea, tear it down and set us free…",
	"STR_INTRO_UMA_05_05": "No! The wand… it's a fake! \nYou don’t get to win every time! Get ‘em!",
	"STR_OUTRO_UMA_05_01": "What’s my name? Say it louder!!!",
	"STR_OUTRO_UMA_05_02": "UMA! UMA!",
	"STR_INTRO_UMA_04_01": "Hey Uma, I followed those dweebs to their ride. All I found was this book.",
	"STR_INTRO_UMA_04_02": "Take a look at it.",
	"STR_INTRO_UMA_04_03": "Mal’s spell book... GIL, YOU’RE A GENIUS! Okay, maybe that’s being a bit generous.",
	"STR_INTRO_UMA_04_04": "But this is great. Maybe not all is lost…",
	"STR_INTRO_UMA_04_05": "Gil, Harry, bring me all these ingredients and meet me in the shop, I’ve got a plan.",
	"STR_OUTRO_UMA_04_01": "Here you go, Uma.",
	"STR_OUTRO_UMA_04_02": "Now what’s the plan?",
	"STR_OUTRO_UMA_04_03": "These are the ingredients for a love potion. Let’s see what this puppy can do.",
	"STR_INTRO_UMA_03_01": "Now I’ve gotta figure out how that loser crossed the barrier.",
	"STR_OUTRO_UMA_03_01": "Purple... really? Ugh.\nNoble steed proud and fair, you shall take me anywhere!",
	"STR_INTRO_UMA_02_01": "So this is Auradon. Nice place. Is this how the other half lives? \nHmm.. I could get used to it…",
	"STR_OUTRO_UMA_01_01": "Uma? How did you get here? I don’t want to call the guards…",
	"STR_OUTRO_UMA_01_02": "Please, Ben. Listen. I thought about what you said back on the Isle. Maybe… maybe we can work together…",
	"STR_OUTRO_UMA_01_03": "Are you serious?",
	"STR_OUTRO_UMA_01_04": "Yes. And as a token of goodwill, I brought you fish and chips.",
	"STR_OUTRO_UMA_01_05": "Here, all for you.",
	"STR_OUTRO_UMA_01_06": "Ugh. I mean… thanks! \nWell, it would be rude not to accept it, right? \nBesides, I’m really hungry...",
	"STR_OUTRO_UMA_01_07": "Wait… what is in this? I feel funny…",
	"STR_OUTRO_UMA_07_01": "I wish I had time to explain.",
	"STR_OUTRO_UMA_07_02": "I have an announcement: \nUma will be joining the court as my lady.",
	"STR_OUTRO_UMA_07_03": "So as my gift to her I’m bringing down the barrier between Auradon and the Isle of the Lost once and for all.",
	"STR_OUTRO_UMA_07_04": "Listen to your king!",
	"STR_OUTRO_UMA_07_05": "Ben? What is this? Something is not right…",
	"STR_INTRO_UMA_BOSS_01": "I won’t let you ruin this… \nI’ll take that wand and break the barrier!",
	"STR_OUTRO_UMA_BOSS_01": "True love kiss won’t defeat this! The world will know my name! \nUMA!!!",
	"STR_OUTRO_UMA_BOSS_02": "Uma, don’t let your pride get in the way of being who you really are. \nI know there's good inside of you!",
	"STR_OUTRO_UMA_BOSS_03": "……………………..",
	"STR_INTRO_BONUS_01": "Uma, Mal… back down. Please!",
	"STR_INTRO_BONUS_02": "What are you gonna do, splash me?",
	"STR_OUTRO_BONUS_01": "That’s enough, you have to stop.  \nThis isn’t the answer, nobody wins this way!!",
	"STR_OUTRO_BONUS_02": "Of course someone wins! I win if I win! Now just let me do this, Ben!",
	"STR_OUTRO_BONUS_03": "We have to listen and respect each other!  \nI know it won’t be easy, but we must be brave enough to try...",
	"STR_OUTRO_BONUS_04": "Easy for you to say! You sit in the lap of luxury in Auradon while the children on the Isle live alone in darkness! \nIs that your idea of ‘listening and respect’ ???",
	"STR_OUTRO_BONUS_05": "Your battle is with me, Uma! Not with him!",
	"STR_OUTRO_BONUS_06": "No… Mal… Uma’s right.",
	"STR_OUTRO_BONUS_07": "Ben… what are you saying?",
	"STR_OUTRO_BONUS_08": "This is wrong… and it’s all my fault. I made this mess…  \nBut I can’t fix it alone…",
	"STR_OUTRO_BONUS_09": "What are you talking about, Prince Charming?",
	"STR_OUTRO_BONUS_10": "We have to stop this. Together. Nobody else can do it but us.\nPlease, Mal… Uma – will you help me?",
	"STR_OUTRO_BONUS_11": "……………………..",
	"STR_OUTRO_BONUS_12": "……………………..",
	"STR_OUTRO_BONUS_13": "Uma, I know you want what’s best for the Isle, help me make a difference.",
	"STR_OUTRO_BONUS_14": "Mal, I messed up. I was blind, forgive me. Help me make this right.",
	"STR_OUTRO_BONUS_15": "Magic wand, your judgment fair… \nmake justice reign both here and there…",
	"STR_MESSAGES_START": "READY",
	"STR_MESSAGES_LEVELCOMPLETE": "LEVEL COMPLETED!",
	"STR_MESSAGES_BOSSCOMPLETE_MAL": "MAL WINS",
	"STR_MESSAGES_BOSSCOMPLETE_UMA": "UMA WINS",
	"STR_MESSAGES_BONUSLEVEL": "BONUS LEVEL UNLOCKED!",
	"STR_MESSAGES_FINALBATTLE": "FINAL BATTLE!",
	"STR_ENDGAME01_TITLE01": "MAL'S STORY COMPLETED !",
	"STR_ENDGAME01_TITLE02": "UMA'S STORY COMPLETED !",
	"STR_ENDGAME01_INFO01": "Uma's Story ",
	"STR_ENDGAME01_INFO02": "Mal's Story ",
	"STR_ENDGAME02_TITLE": "THANKS FOR PLAYING!",
	"STR_TUTORIAL_INFO01": "You automatically climb low obstacles ",
	"STR_TUTORIAL_INFO02": "Jump while climbing for an extra boost ",
	"STR_TUTORIAL_INFO03": "If you jump into a wall you'll bounce back ",
	"STR_TUTORIAL_INFO04": "Do tricks, flips and jumps off poles and other items to fill your Rush Meter.",
	"STR_TUTORIAL_INFO05": "Fill your Rush Meter to go farther, faster and collect special items.",
	"STR_TUTORIAL_INFO06": "Swipe to attack  ",
	"STR_TUTORIAL_INFO06PC": "Press X to attack  ",
	"STR_TUTORIAL_INFO07": "You can also hop on enemies.  ",
	"STR_TUTORIAL_INFO08": "Tap to jump ",
	"STR_TUTORIAL_INFO08PC": "Press Z to jump ",
	"STR_TUTORIAL_LETTER01": "Z",
	"STR_TUTORIAL_LETTER02": "X",
	"STR_TUTORIAL_BONUS_INFO1": "Tap to dodge attacks",
	"STR_TUTORIAL_BONUS_INFO2": "Break the shield! Swipe to attack",
	"STR_TUTORIAL_BONUS_INFO1PC": "Press Z to dodge attacks",
	"STR_TUTORIAL_BONUS_INFO2PC": "Break the shield! Press X to attack",
	"STR_TAPTOCONTINUE": "Tap to continue",
	"STR_TAPTOCONTINUEPC": "Press SPACEBAR to continue",
	"STR_TRANSFORMATION_MAL_NAME01": "AURADON OUTFIT ",
	"STR_TRANSFORMATION_MAL_NAME02": "VK Outfit",
	"STR_TRANSFORMATION_MAL_NAME03": "Party Dress",
	"STR_TRANSFORMATION_INFO01": "NEW OUTFIT!",
	"STR_TRANSFORMATION_UMA_NAME01": "AURADON ",
	"STR_TRANSFORMATION_UMA_NAME02": "Pirate Outfit",
	"STR_TRANSFORMATION_UMA_NAME03": "Party Dress",
	"STR_BOSS_VS": "VS",
	"STR_CUTSCENE01_01": "Being the ‘perfect Auradon girl’ was way more work than Mal expected!",
	"STR_CUTSCENE01_02": "All the duties, manners and expectations – she could only keep up with everything by using her spell book…",
	"STR_CUTSCENE01_03": "But when her secret was revealed – it ruined her special date with Ben.",
	"STR_CUTSCENE01_04": "That was it. Mal knew she could never be a ‘perfect Auradon girl’ – \nmaybe she spent too much time trying to be something she wasn’t…",
	"STR_CUTSCENE02_01": "Back when Mal, Evie, Carlos and Jay decided to stay in Auradon, they left behind other VK’s who took their place on the Isle of the Lost.",
	"STR_CUTSCENE02_02": "A girl named Uma became the new leader of the Isle. Fed up with Mal’s lucky break, she devised a plan to get revenge on her and Auradon, too.",
	"STR_CUTSCENE03_01": "MAL: Fairy Godmother… this book seriously belongs in a museum!",
	"STR_CUTSCENE03_02": "EVIE: True love’s kiss, works every time.",
	"STR_CUTSCENE04_01": "UMA: What, you didn’t think this was the end of the story?",
	"STR_CUTSCENE05_01": "UMA: THE WORLD WILL KNOW MY NAME!",
	"STR_MESSAGES_CHECKPOINT": "CHECKPOINT!"
};
