ig.strings =
{
	SWITCH_GAME_TO_BOOK : { text : 'Are you sure you want to leave and explore the travel guide?' },
	SWITCH_GAME_TO_MAP : { text : 'Are you sure you want to leave and explore the map?' },
	
	BOOK: {

		DEFAULT_STYLES:{
			// DO NOT EDIT FALLBACK
			FALLBACK:{ font: 'Superclarendon', style: '', size:'30px', color:'#4a3f30'},
			INPUT_TEXT_BOX:{ font: 'Superclarendon', style: 'bold', size:'30px', color:'#4a3f30'},
			MAIN_MENU_TITLE:{ font:'Superclarendon', style: 'bold italic', size:'22px', color:'#4a3f30', textAlign:'center', textBaseline:'middle' },
			MAIN_MENU_BUTTONS:{ font:'Superclarendon', style: 'bold italic', size:'36px', color:'#4a3f30', textAlign:'center', textBaseline:'middle' },
			BIG_BUTTONS:{ font:'Superclarendon', style: 'bold italic', size:'42px', color:'#4a3f30', textAlign:'center', textBaseline:'middle' },
			SMALL_BUTTONS: { font:'Superclarendon', style: 'bold italic', size:'36px', color:'#4a3f30', textAlign:'center', textBaseline:'middle' },
			GIANT_BUTTONS: { font:'Superclarendon', style: 'bold italic', size:'46px', color:'#4a3f30', textAlign:'center', textBaseline:'middle' },

			ACTIVITY_TITLE: { font:'Superclarendon', style: 'bold italic', size:'40px', color:'#4a3f30', textAlign:'center', textBaseline:'middle', lineWidth:"300" },
			ACTIVITY_SUB_TITLE: { font:'Superclarendon', style: 'bold italic', size:'26px', color:'#4a3f30', textAlign:'center', textBaseline:'middle', lineWidth:"300" },
			ACTIVITY_SUB_TITLE_LEFT: { font:'Superclarendon', style: 'bold italic', size:'26px', color:'#4a3f30', textAlign:'left', textBaseline:'middle', lineWidth:"300" },
			ACTIVITY_DESCRIPTION: { font:'Superclarendon', style: 'lighter', size:'22px', color:'#4a3f30', textAlign:'left', textBaseline:'top', lineWidth:'327', lineHeight:'35' },
			QUIZ_QUESTION: { font:'Superclarendon', style: 'bold italic', size:'24px', color:'#4a3f30', textAlign:'left', textBaseline:'top', lineWidth:'300', lineHeight:'45' },
			QUIZ_NUMBERS: { font:'Superclarendon', style: 'bold italic', size:'44px', color:'#4a3f30', textAlign:'center', textBaseline:'middle', lineWidth:"300" },
			QUIZ_ANSWERS: { font:'Superclarendon', style: 'lighter', size:'24px', color:'#4a3f30', textAlign:'left', textBaseline:'middle', lineWidth:'280', lineHeight:'30' },
			QUIZ_GRADE_TITLE: { font:'Superclarendon', style: 'bold italic', size:'38px', color:'#4a3f30', textAlign:'center', textBaseline:'middle', lineWidth:"400" },
			QUIZ_FINAL_GRADE: { font:'Superclarendon', style: 'bold italic', size:'102px', color:'#cf270a', textAlign:'center', textBaseline:'middle'},

			MUSEUM_TITLE_LEFT: { font:'Superclarendon', style: 'bold italic', size:'28px', color:'#4a3f30', textAlign:'left', textBaseline:'middle', lineWidth:'260', lineHeight:'40'},
			MUSEUM_NUMBERS: { font:'Superclarendon', style: 'bold italic', size:'24px', color:'#4a3f30', textAlign:'center', textBaseline:'middle'},
			MUSEUM_DESC: { font:'Superclarendon', style: 'lighter', size: '22px', color:'#4a3f30', textAlign:'left', lineWidth:'300', lineHeight:'40'},
			MUSEUM_STOLEN:{ font:'Gnuolane', style: 'bold', size: '90px', color:'#cf270a', textAlign:'center'},
			MUSEUM_PLAY: { font:'Superclarendon', style:'bold italic', size:'18px', color:'#493e30', textAlign:'center' },
			
			PASSPORT_LABEL:{ font:'Superclarendon', style:'bold italic', size:'26px', color:'#dddddd', alpha:'0.7' },
			PASSPORT_1:{ font:'Superclarendon', style:'bold italic', size:'16px', color:'#000000', textAlign:'center' },
			PASSPORT_2:{ font:'Gnuolane', style:'bold', size:'32px', color:'#000000', textAlign:'center' },
			PASSPORT_3:{ font:'Gnuolane', style:'bold', size:'20px', color:'#000000', textAlign:'left' },
			PASSPORT_4:{ font:'Gnuolane', style:'bold', size:'12px', color:'#000000', textAlign:'left' },
			PASSPORT_NAME:{ font:'Gnuolane', style:'bold italic', size:'22px', color:'#000000', textAlign:'left' },
			PASSPORT_PRINT:{ font:'Superclarendon', style:'bold italic', size:'26px', color:'#493e30', textAlign:'center' },
			PASSPORT_GOTO:{ font:'Superclarendon', style:'bold italic', size:'16px', color:'#493e30', textAlign:'center' },
			PASSPORT_MAP:{ font:'Superclarendon', style:'bold italic', size:'42px', color:'#493e30', textAlign:'center' },
			PASSPORT_STAMP_TITLE: { font:'Superclarendon', style: 'bold italic', size:'26px', color:'#4a3f30', textAlign:'center', textBaseline:'middle', lineWidth:"400" },
		},

		MAIN_MENU : {
			TITLE: 				{ text:"Museum Map" },
			ITEM_NAMES:{
				ITEM_STOLEN: 	{ text:"Item Stolen!" },
				ITEM_1:			{ text:"The Rose" },
				ITEM_2:			{ text:"Spinning Wheel" },
				ITEM_3:			{ text:"Poseidon's Trident" },
				ITEM_4:			{ text:"Poison Apple" },
				ITEM_5:			{ text:"Magic Wand" }
			},
			BUTTONS:{
				QUIZ: 			{ text:"Quiz" },
				MUSEUM: 		{ text:"Museum" },
				PASSPORT: 		{ text:"Passport" },
				MAP: 			{ text:"Map" }
			}
		},
		TEST :{
			TITLE: 				{ text:"Enchanted History 101"},
			START_BUTTON: 		{ text: "START" },
			RETRY_BUTTON: 		{ text: "Retry" },
			SCORE: 				{ text: "%N / %NN" },
			TEST_QUESTIONS:	{
				QUESTION_1 : 				{ text : "Cinderella's dog and horse's names' are:" },
				CORRECT_ANSWER_1 : 			{ text : "Bruno and Major" },
				INCORRECT_ANSWER_1_1 : 		{ text : "Pluto and Majesty"},
				INCORRECT_ANSWER_1_2 : 		{ text : "Charlie and Charlotte"},
				INCORRECT_ANSWER_1_3 : 		{ text : "Duke and Dutchess"},
				QUESTION_2 : 				{ text : "Who awakens Sleeping Beauty with true love's kiss?" },
				CORRECT_ANSWER_2 : 			{ text : "Prince Philip" },
				INCORRECT_ANSWER_2_1 : 		{ text : "Prince Charming" },
				INCORRECT_ANSWER_2_2 : 		{ text : "Prince Florian" },
				INCORRECT_ANSWER_2_3 : 		{ text : "Prince Hans of the Southern Isles" },
				QUESTION_3 : 				{ text : "Mulan's dog's name is:" },
				CORRECT_ANSWER_3 : 			{ text : "Little Brother" },
				INCORRECT_ANSWER_3_1 : 		{ text : "Hayabusa" },
				INCORRECT_ANSWER_3_2 : 		{ text : "General Li" },
				INCORRECT_ANSWER_3_3 : 		{ text : "Mutt-Mutt" },
				QUESTION_4 : 				{ text : "The dalmatian parents in 101 Dalmatians are:" },
				CORRECT_ANSWER_4 : 			{ text : "Pongo and Perdita" },
				INCORRECT_ANSWER_4_1 : 		{ text : "Anna and Kristoff" },
				INCORRECT_ANSWER_4_2 : 		{ text : "Rapunzel and Flynn" },
				INCORRECT_ANSWER_4_3 : 		{ text : "Roger and Anita" },
				QUESTION_5 : 				{ text : "Mulan joins the army disguised as a soldier named:" },
				CORRECT_ANSWER_5 : 			{ text : "Ping" },
				INCORRECT_ANSWER_5_1 : 		{ text : "Mushu" },
				INCORRECT_ANSWER_5_2 : 		{ text : "Chen" },
				INCORRECT_ANSWER_5_3 : 		{ text : "Liko" },
				QUESTION_6 : 				{ text : "The seven dwarves work in:" },
				CORRECT_ANSWER_6 : 			{ text : "A diamond mine" },
				INCORRECT_ANSWER_6_1 : 		{ text : "A farmer's market" },
				INCORRECT_ANSWER_6_2 : 		{ text : "The king's stables" },
				INCORRECT_ANSWER_6_3 : 		{ text : "A dungeon" },
				QUESTION_7 : 				{ text : "Ariel trades this item for a pair of human legs:" },
				CORRECT_ANSWER_7 : 			{ text : "Her voice" },
				INCORRECT_ANSWER_7_1 : 		{ text : "Her long hair" },
				INCORRECT_ANSWER_7_2 : 		{ text : "A dinglehopper" },
				INCORRECT_ANSWER_7_3 : 		{ text : "An apple" },
				QUESTION_8 : 				{ text : "Cinderella's stepmother's name is:" },
				CORRECT_ANSWER_8 : 			{ text : "Lady Tremaine" },
				INCORRECT_ANSWER_8_1 : 		{ text : "Dutchess White" },
				INCORRECT_ANSWER_8_2 : 		{ text : "Lady Chaplin" },
				INCORRECT_ANSWER_8_3 : 		{ text : "Countess Davies" },
				QUESTION_9 : 				{ text : "As a child, Maleficent lived in:" },
				CORRECT_ANSWER_9 : 			{ text : "The Moors" },
				INCORRECT_ANSWER_9_1 : 		{ text : "Wonderland" },
				INCORRECT_ANSWER_9_2 : 		{ text : "Auradon" },
				INCORRECT_ANSWER_9_3 : 		{ text : "The Enchanted Forest" },
				QUESTION_10 : 				{ text : "Jafar never leaves home without his:" },
				CORRECT_ANSWER_10 : 		{ text : "Cobra-headed staff" },
				INCORRECT_ANSWER_10_1 : 	{ text : "Wallet" },
				INCORRECT_ANSWER_10_2 : 	{ text : "Snake-in-a-basket" },
				INCORRECT_ANSWER_10_3 : 	{ text : "Magic lamp" },
				QUESTION_11 : 				{ text : "When Belle returns home, who stows away in her bag?" },
				CORRECT_ANSWER_11 : 		{ text : "Chip" },
				INCORRECT_ANSWER_11_1 : 	{ text : "Lumiere" },
				INCORRECT_ANSWER_11_2 : 	{ text : "Mrs. Potts" },
				INCORRECT_ANSWER_11_3 : 	{ text : "Coggsworth" },
				QUESTION_12 : 				{ text : "Who is Mother Gothel's \"adopted\" daughter?" },
				CORRECT_ANSWER_12 : 		{ text : "Rapunzel"}, 
				INCORRECT_ANSWER_12_1 : 	{ text : "Cinderella"},
				INCORRECT_ANSWER_12_2 : 	{ text : "Belle"},
				INCORRECT_ANSWER_12_3 : 	{ text : "Briar Rose"},
				QUESTION_13 : 				{ text : "Fairy Godmother turned Cinderella's horse into:" },
				CORRECT_ANSWER_13 : 		{ text : "A coachman" },
				INCORRECT_ANSWER_13_1 : 	{ text : "A carriage" },
				INCORRECT_ANSWER_13_2 : 	{ text : "A pair of glass slippers" },
				INCORRECT_ANSWER_13_3 : 	{ text : "A footman" },
				QUESTION_14 : 				{ text : "Which of the following is not a fairy?" },
				CORRECT_ANSWER_14 : 		{ text : "Rapunzel" },
				INCORRECT_ANSWER_14_1 : 	{ text : "Flora" },
				INCORRECT_ANSWER_14_2 : 	{ text : "Merryweather" },
				INCORRECT_ANSWER_14_3 : 	{ text : "Fauna" },
				QUESTION_15 : 				{ text : "Anna and Elsa's parents:" },
				CORRECT_ANSWER_15 : 		{ text : "Were lost at sea" },
				INCORRECT_ANSWER_15_1 : 	{ text : "Bought a timeshare in Wonderland" },
				INCORRECT_ANSWER_15_2 : 	{ text : "Moved to Neverland" },
				INCORRECT_ANSWER_15_3 : 	{ text : "Went on a long road trip" },
				QUESTION_16 : 				{ text : "Prince Philip first meets Princess Aurora:" },
				CORRECT_ANSWER_16 : 		{ text : "At her christening as a baby" },
				INCORRECT_ANSWER_16_1 : 	{ text : "In the Enchanted Forest" },
				INCORRECT_ANSWER_16_2 : 	{ text : "In Maleficent's dungeon" },
				INCORRECT_ANSWER_16_3 : 	{ text : "At the fairies' cottage" },
				QUESTION_17 : 				{ text : "Anita and Cruella De Vil:" },
				CORRECT_ANSWER_17 : 		{ text : "Went to the same school" },
				INCORRECT_ANSWER_17_1 : 	{ text : "Met at the supermarket" },
				INCORRECT_ANSWER_17_2 : 	{ text : "Met at a dog obedience school" },
				INCORRECT_ANSWER_17_3 : 	{ text : "Belong to the same book club" },
				QUESTION_18 : 				{ text : "Where does Aladdin find the Magic Lamp?" },
				CORRECT_ANSWER_18 : 		{ text : "In the Cave of Wonders" },
				INCORRECT_ANSWER_18_1 : 	{ text : "At the Agrabah Market" },
				INCORRECT_ANSWER_18_2 : 	{ text : "In the diamond mines" },
				INCORRECT_ANSWER_18_3 : 	{ text : "In Princess Jasmine's palace" },
				QUESTION_19 : 				{ text : "Snow White falls into a deep sleep:" },
				CORRECT_ANSWER_19 : 		{ text : "After taking a bite of a poison apple" },
				INCORRECT_ANSWER_19_1 : 	{ text : "After cleaning up the dwarves' cottage" },
				INCORRECT_ANSWER_19_2 : 	{ text : "After getting lost in the Enchanted Forest" },
				INCORRECT_ANSWER_19_3 : 	{ text : "After studying for a midterm" },
				QUESTION_20 : 				{ text : "Why does Snow White live with the Evil Queen?" },
				CORRECT_ANSWER_20 : 		{ text : "She is her step mother" },
				INCORRECT_ANSWER_20_1 : 	{ text : "She is her aunt" },
				INCORRECT_ANSWER_20_2 : 	{ text : "She is her neighbor" },
				INCORRECT_ANSWER_20_3 : 	{ text : "She stole Snow White as a baby" },
				QUESTION_21 : 				{ text : "Cinderella's curfew the night of the ball was:" },
				CORRECT_ANSWER_21 : 		{ text : "The final stroke of midnight" },
				INCORRECT_ANSWER_21_1 : 	{ text : "Whenever she felt tired" },
				INCORRECT_ANSWER_21_2 : 	{ text : "After the final dance" },
				INCORRECT_ANSWER_21_3 : 	{ text : "After dessert was served" },
				QUESTION_22 : 				{ text : "Why does Mulan join the army?" },
				CORRECT_ANSWER_22 : 		{ text : "In place of her elderly father" },
				INCORRECT_ANSWER_22_1 : 	{ text : "To experience new adventures" },
				INCORRECT_ANSWER_22_2 : 	{ text : "To avoid an arranged marriage" },
				INCORRECT_ANSWER_22_3 : 	{ text : "To get away from her parents" },
				QUESTION_23 : 				{ text : "Aladin's pet monkey's name is:" },
				CORRECT_ANSWER_23 : 		{ text : "Abu" },
				INCORRECT_ANSWER_23_1 : 	{ text : "Pascal" },
				INCORRECT_ANSWER_23_2 : 	{ text : "Bambi" },
				INCORRECT_ANSWER_23_3 : 	{ text : "Baloo" },
				QUESTION_24 : 				{ text : "Princess Aurora..." },
				CORRECT_ANSWER_24 : 		{ text : "Is an only child" },
				INCORRECT_ANSWER_24_1 : 	{ text : "Has a younger sister" },
				INCORRECT_ANSWER_24_2 : 	{ text : "Has an older sister" },
				INCORRECT_ANSWER_24_3 : 	{ text : "Has an older brother" },
				QUESTION_25 : 				{ text : "Cinderella's stepsisters are named:" },
				CORRECT_ANSWER_25 : 		{ text : "Anastasia and Drizella" },
				INCORRECT_ANSWER_25_1 : 	{ text : "Anna and Elsa" },
				INCORRECT_ANSWER_25_2 : 	{ text : "Alana and Ariel" },
				INCORRECT_ANSWER_25_3 : 	{ text : "Belle and Babette" },
				QUESTION_26 : 				{ text : "Who gives Evil Queen the bad news about her looks?" },
				CORRECT_ANSWER_26 : 		{ text : "Her magic mirror" },
				INCORRECT_ANSWER_26_1 : 	{ text : "Her crystal ball" },
				INCORRECT_ANSWER_26_2 : 	{ text : "Diablo the raven" },
				INCORRECT_ANSWER_26_3 : 	{ text : "The Golden Egg" },
				QUESTION_27 : 				{ text : "Perdita gives birth to how many dalmatians?" },
				CORRECT_ANSWER_27 : 		{ text : "15" },
				INCORRECT_ANSWER_27_1 : 	{ text : "101" },
				INCORRECT_ANSWER_27_2 : 	{ text : "12" },
				INCORRECT_ANSWER_27_3 : 	{ text : "84" },
				QUESTION_28 : 				{ text : "Rapunzel's best friend Pascal is:" },
				CORRECT_ANSWER_28 : 		{ text : "A chameleon" },
				INCORRECT_ANSWER_28_1 : 	{ text : "A frog" },
				INCORRECT_ANSWER_28_2 : 	{ text : "A horse" },
				INCORRECT_ANSWER_28_3 : 	{ text : "A mouse" },
				QUESTION_29 : 				{ text : "Fairy Godmother's magical phrase is:" },
				CORRECT_ANSWER_29 : 		{ text : "Bibidi-bobidi-boo!" },
				INCORRECT_ANSWER_29_1 : 	{ text : "Hocus Pocus!" },
				INCORRECT_ANSWER_29_2 : 	{ text : "Rumpelstiltskin!" },
				INCORRECT_ANSWER_29_3 : 	{ text : "Abracadabra!" },
				QUESTION_30 : 				{ text : "Princess Jasmine's father is:" },
				CORRECT_ANSWER_30 : 		{ text : "The Sultan of Agrabah" },
				INCORRECT_ANSWER_30_1 : 	{ text : "Mr. Darling" },
				INCORRECT_ANSWER_30_2 : 	{ text : "King Triton" },
				INCORRECT_ANSWER_30_3 : 	{ text : "King Mufasa" },
			},
			RESULT:{
				G10: { text: "A" },
				G9: { text: "A" },
				G8: { text: "B" },
				G7: { text: "C" },
				G6: { text: "D" },
				G5: { text: "F" },
				G4: { text: "F" },
				G3: { text: "F" },
				G2: { text: "F" },
				G1: { text: "F" },
				G0: { text: "F" },
				SUCCESS:	{ text:"Success!\nYour Grade is:"},
				FAIL:		{ text:"Oops!\nYour grade is:"}
			}
		},
		MUSEUM : {
			TITLE: 				{ text:"THE MUSEUM of CULTURAL HISTORY" },
			SUB_TITLE: 			{ text:"Artifact Guide" },
			DESCRIPTION:		{ text:"This isn’t your average museum. It contains magical objects; some used to do good, and others to bestow evil. Proceed with caution." },
			FIND_IT_BUTTON: 	{ text:"find it on the" },
			STOLEN: 			{ text:"STOLEN" },
			PLAY_BUTTON: 		{ text:"play" },
			REPLAY_BUTTON: 		{ text:"replay" },
			ITEMS: {
				TITLE_1:		{ text:"Fairy Godmother's Wand:" },
				DESCRIPTION_1:	{ text:"Beauty is in the eye of the beholder, and Fairy Godmother thinks her daughter Jane is a natural beauty. No magic wand could ever change that!"},
				TITLE_2:		{ text:"Maleficent's Spinning Wheel:" },
				DESCRIPTION_2:	{ text:"Mal’s mom is her world, but when Mal is suddenly thrust into a new world, everything changes!  Can following your own heart break someone else's?"},
				TITLE_3:		{ text:"Diamonds:" },
				DESCRIPTION_3:	{ text:"Who says diamonds are only a girl’s best friend? It’s all in a day’s work for Doug’s dad, Dopey, but Doug would rather give them as gifts!"},
				TITLE_4:		{ text:"Beast's Enchanted Rose:" },
				DESCRIPTION_4:	{ text:"Ruled by King Beast and Queen Belle, Auradon is a peaceful land of united kingdoms. Those who were truly evil were banished to the Isle of The Lost."},
				TITLE_5:		{ text:"Cherry Blossom:" },
				DESCRIPTION_5:	{ text:"Lonnie’s mom Mulan is a legend, and behind the legend is a strong family bond. Lonnie’s compassion is one of her most redeeming qualities."},
				TITLE_6:		{ text:"Magic Mirror Shard:" },
				DESCRIPTION_6:	{ text:"She may be the daughter of the Evil Queen, but Evie has a heart of gold. No magic mirror needed!"},
				TITLE_7:		{ text:"Prince Charming’s Sword:" },
				DESCRIPTION_7:	{ text:"His charming ways have helped Prince Chad all of his life, but he could try using them in a more honest and sincere manner."},
				TITLE_8:		{ text:"Jafar’s Turban:" },
				DESCRIPTION_8:	{ text:"Jay’s father may have a way with magic lamps, but he’s not interested in following in Jafar’s footsteps. A game of tourney is more his style!"},
				TITLE_9:		{ text:"Aurora's Basket:" },
				DESCRIPTION_9:	{ text:"As a princess, Audrey’s confidence and beauty are traits that come in handy, but inner beauty can be just as important a quality to possess."},
				TITLE_10:		{ text:"Cruella's Boots:" },
				DESCRIPTION_10:	{ text:"A dog is not man’s best friend, that’s what Carlos’ mom Cruella told him. Not having a pet is probably why he loves making new friends!"}
			}
		},
		PASSPORT : {

			TITLE_0:			{ text:"Create your Passport"},
			DESCRIPTION:		{ text:"Hello visitor!  Whether you traveled here by fairy dust, beanstalk or magic carpet, why not make your vacation here permanent? Want to be a citizen of Auradon or The Isle of the Lost? The choice is yours to make!"},
			TITLE_1:			{ text:"Make your choice"},
			SELECTION_OR: 		{ text:"or"},
			TITLE_2:			{ text:"Upload photo"},
			TITLE_3:			{ text:"Add your name"},
			TITLE_4:			{ text:"Collect stamps from locations on the map."},
			PASSPORT: 			{ text:"Passport"},
			SUB_TITLE_1:		{ text:"Goodness begins with you"},
			SUB_TITLE_2:		{ text:"UNITED STATES OF AURADON"},
			SUB_TITLE_3:		{ text:"AURADON"},
			SUB_TITLE_4:		{ text:"Home Country"},
			SUB_TITLE_5:		{ text:"DATE OF ISSUE"},
			SUB_TITLE_6:		{ text:"GIVEN NAME"},
			DATE:				{ text:"%MM/%DD/%YYYY"},

			SUB_TITLE_7:		{ text:"Long Live Evil!"},
			SUB_TITLE_8:		{ text:"ISLE OF THE LOST"},
			SUB_TITLE_9:		{ text:"ISLE OF THE LOST"},
			BUTTON_UPLOAD: 		{ text:"UPLOAD"},
			BUTTON_CHOOSE: 		{ text:"CHOOSE"},
			BUTTON_PRINT: 		{ text:"PRINT"},
			GO_TO_THE: 			{ text:"go to the"},
			MAP: 				{ text:"MAP"}
		}
	},
	USER_INTERFACE:{
		MAIN_MENU_BUTTONS:{
			BUTTON_QUIZ:		{ text:"Quiz"},
			BUTTON_MUSEUM:		{ text:"Museum"},
			BUTTON_PASSPORT:	{ text:"Passport"}, 
			BUTTON_MAP:			{ text:"Map"}
		},
		MISC_BUTTONS:{
			START_BUTTON:		{ text:"START"},
			PLAY_BUTTON:		{ text:"play"},
			RETRY_BUTTON:		{ text:"Retry"},
			FIND_BUTTON:		{ text:"find it on the MAP"},
			UPLOAD_BUTTON:		{ text:"UPLOAD"},
			CHANGE_BUTTON:		{ text:"CHANGE"}
		},
		NUMBERS_0: 		{ text: "0."},
		NUMBERS_1: 		{ text: "1."},
		NUMBERS_2: 		{ text: "2."},
		NUMBERS_3: 		{ text: "3."},
		NUMBERS_4: 		{ text: "4."},
		NUMBERS_5: 		{ text: "5."},
		NUMBERS_6: 		{ text: "6."},
		NUMBERS_7: 		{ text: "7."},
		NUMBERS_8: 		{ text: "8."},
		NUMBERS_9: 		{ text: "9."},
		NUMBERS_10: 	{ text: "10."}
	},

	MAP :
	{
		LOADER :
		{
			RIGHT : { text : '100 MILES' },
			MIDDLE : { text : '50 MILES' },
			LEFT : { text : 'I' },
			BOTTOM : { text : 'SCALE 1:2300' }
		},

		PRINT : { text : 'You found the missing museum artifacts and completed your passport! Print your own map of Auradon and add your passport stamps to it!' }
	},

	SEARCH :
	{
		LEVEL_1 : 
		{
			STORY : { text : '“Welcome to Auradon! I’m Prince Ben, and I live in a castle with my parents, King Beast and Queen Belle. I go to a great school and I have some awesome friends, I can’t complain! I’ve got a big tourney game this afternoon, and I can’t find my class ring anywhere. Can you help me find it?”' },
			END_NOTE : { text : 'You think you’re so clever. Why should these objects sit in a museum, when they could be put to good use? I’m heading for the school. Stay away!\n-D' }
		},

		LEVEL_2 : 
		{
			STORY : { text : '“Hi, it’s me, Evie. In a word, Auradon’s “interesting.” I’ve been keeping busy with school, it’s definitely different than my old school on The Isle of The Lost. Our dorm room is so… colorful. It needs a personal touch to make it feel like home. Mal’s always so busy. Can you help me?”' },
			END_NOTE : { text : 'Who sent you to follow me? What I need has no meaning to you. My spells are more powerful than anything in a silly book. Follow me if you dare.\n-D' }
		},

		LEVEL_3 : 
		{
			STORY : { text : '“Have we met? I’m Mal, as in Maleficent’s daughter. You’ve seen one kitchen, you’ve seen them all, so I wouldn’t say this is anything special. I don’t know how long I’m going to be in Auradon, and it’s too quiet for my taste. Let’s come up with a plan to make some waves. Are you in?”' },
			END_NOTE : { text : 'This is your last warning. My plan for the artifacts is working, and where I’m going, you cannot follow. You are not one of the Lost.\n-D' }
		},

		LEVEL_4 : 
		{
			STORY : { text : '“Carlos and I know this place like the back of our hands. Hang out with us long enough and you might discover its secrets, and secret hiding places! We’re not like the kids next door in Auradon. We’re proof that the apple doesn’t fall far from the tree.”' },
			END_NOTE : { text : 'You’ve won this time, but my next plan is bigger than all of this; something that’s never been done before. You’ll see me again.\nBe warned!\n-D' }
		},

		ITEM_FOUND : { text : 'You found' },
		ITEM :
		{
			// level 1
			BACKPACK : { text : 'Backpack' },
			BALL : { text : 'Tourney Ball' },
			CANDLE : { text : 'Candle Stick' },
			CREST : { text : 'Crest' },
			CROWN : { text : 'Crown' },
			GLOVE : { text : 'Tourney Glove' },
			RING : { text : 'Ring' },
			SHOES : { text : 'Shoes' },
			TOURNEYSTICK : { text : 'Tourney Stick' },
			STAMP1 : { text : 'Stamp' },

			// level 2
			BRUSH : { text : 'Brush' },
			DOG : { text : 'Dude' },
			MAKEUP : { text : 'Makeup' },
			MIRROR : { text : 'Mirror' },
			PENDANT : { text : 'Pendant' },
			SKETCHBOOK : { text : 'Sketchbook' },
			SLEEPINGSPRAY : { text : 'Sleeping Spray' },
			SPRAYPAINT : { text : 'Spray Paint' },
			THREAD : { text : 'Thread' },
			STAMP2 : { text : 'Stamp' },

			// level 3
			CHOCOLATECHIPS : { text : 'Chocolate Chips' },
			COOKIE : { text : 'Cookie' },
			CUPCAKE : { text : 'Cupcake' },
			MEASURINGCUP : { text : 'Measuring Cup' },
			MILK : { text : 'Milk' },
			PURSE : { text : 'Purse' },
			ROLLINGPIN : { text : 'Rolling Pin' },
			SPOON : { text : 'Spoon' },
			TRAY : { text : 'Tray' },
			STAMP3 : { text : 'Stamp' },

			// level 4
			APPLE : { text : 'Apple' },
			BASKET : { text : 'Basket' },
			CLOCK : { text : 'Clock' },
			CRYSTALBALL : { text : 'Crystal Ball' },
			KETTLE : { text : 'Kettle' },
			ROSE : { text : 'Rose' },
			SPINNINGWHEEL : { text : 'Spinning Wheel' },
			SWORD : { text : 'Sword' },
			WAND : { text : 'Wand' },
			STAMP4 : { text : 'Stamp' }
		}
	}
};


ig.module('strings').defines();