
var loading = {
	"loading": {
		type: "movieclip",
		fps: 30,
		totalFrames: 33,
		labels: {idle: {from:0, to:4}, out: {from:5, to:32}, },
		layers: [
			{
				name: "bg_x",
				keys: [
					{
						from: 0,
						to: 32,
						classname: "_loading_bg_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 640, ty: 360},
						transform: [640, 360, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "light",
				keys: [
					{
						from: 0,
						to: 32,
						classname: "_loading_light",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "Layer 7",
				keys: [
					{
						from: 0,
						to: 32,
						classname: "_loading_displayclock",
						instancename: "clock",
						matrix: {a: 0.993, b: -0.065, c: 0.101, d: 1, tx: 678.2, ty: 356.2},
						transform: [678.2, 356.2, 0.996, 1.005, 0.101, -0.065, NaN],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "Layer 8",
				keys: [
					{
						from: 0,
						to: 25,
					},
					{
						from: 26,
						to: 31,
						classname: "_loading_whity_x",
						instancename: "",
						matrix: {a: 15.505, b: 0, c: 0, d: 8.786, tx: 650.95, ty: 366.9},
						transform: [650.95, 366.9, 15.505, 8.786, 0, 0, 0],
						alpha: 0,
						visible: true,
						tween: true,
						easing: {
							all: [[0, 0], [0.52, 0], [0.75, 0.589], [1, 1], ],
						}
					},
					{
						from: 32,
						to: 32,
						classname: "_loading_whity_x",
						instancename: "",
						matrix: {a: 15.505, b: 0, c: 0, d: 8.786, tx: 650.95, ty: 366.9},
						transform: [650.95, 366.9, 15.505, 8.786, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "code",
				keys: [
					{
						from: 0,
						to: 3,
					},
					{
						from: 4,
						to: 4,
						actions: function(self){self.stop();},
					},
					{
						from: 5,
						to: 31,
					},
					{
						from: 32,
						to: 32,
						actions: function(self){self.stop();
globalsignal.emit(self, "exit");},
					},
				]
			},
			{
				name: "label",
				keys: [
					{
						from: 0,
						to: 4,
					},
					{
						from: 5,
						to: 32,
					},
				]
			},
		]
	},
	"_loading_bg_x": {
		type: "bitmap",
		asset: "_loading_bg_x",
		scale: 1,
		position: [-645, -365],
	},
	"_loading_light": {
		type: "movieclip",
		fps: 30,
		totalFrames: 43,
		labels: {},
		layers: [
			{
				name: "Layer 1",
				keys: [
					{
						from: 0,
						to: 19,
						classname: "_loading_light_gfx",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: true,
						easing: {
							all: [[0, 0], [0.6, 0], [0.5, 1], [1, 1], ],
						}
					},
					{
						from: 20,
						to: 41,
						classname: "_loading_light_gfx",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 0.56,
						visible: true,
						tween: true,
						easing: {
							all: [[0, 0], [0.6, 0], [0.5, 1], [1, 1], ],
						}
					},
					{
						from: 42,
						to: 42,
						classname: "_loading_light_gfx",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
		]
	},
	"_loading_displayclock": {
		type: "movieclip",
		fps: 30,
		totalFrames: 105,
		labels: {},
		layers: [
			{
				name: "alarmaglow_anima",
				keys: [
					{
						from: 0,
						to: 99,
					},
					{
						from: 100,
						to: 104,
						classname: "_loading_alarmaglow_anima",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 29.5, ty: -0.9},
						transform: [29.5, -0.9, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "buttonglow_anima",
				keys: [
					{
						from: 0,
						to: 99,
					},
					{
						from: 100,
						to: 104,
						classname: "_loading_buttonglow_anima",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -235.7, ty: -239.5},
						transform: [-235.7, -239.5, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "digital_0_x",
				keys: [
					{
						from: 0,
						to: 104,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -210.25, ty: 53.75},
						transform: [-210.25, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "digital_0_x",
				keys: [
					{
						from: 0,
						to: 0,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 1,
						to: 1,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 2,
						to: 2,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 3,
						to: 3,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 4,
						to: 4,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 5,
						to: 5,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 6,
						to: 6,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 7,
						to: 7,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 8,
						to: 8,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 9,
						to: 9,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 10,
						to: 10,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 11,
						to: 11,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 12,
						to: 12,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 13,
						to: 13,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 14,
						to: 14,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 15,
						to: 15,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 16,
						to: 16,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 17,
						to: 17,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 18,
						to: 18,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 19,
						to: 19,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 20,
						to: 20,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 21,
						to: 21,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 22,
						to: 22,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 23,
						to: 23,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 24,
						to: 24,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 25,
						to: 25,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 26,
						to: 26,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 27,
						to: 27,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 28,
						to: 28,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 29,
						to: 29,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 30,
						to: 30,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 31,
						to: 31,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 32,
						to: 32,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 33,
						to: 33,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 34,
						to: 34,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 35,
						to: 35,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 36,
						to: 36,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 37,
						to: 37,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 38,
						to: 38,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 39,
						to: 39,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 40,
						to: 40,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 41,
						to: 41,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 42,
						to: 42,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 43,
						to: 43,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 44,
						to: 44,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 45,
						to: 45,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 46,
						to: 46,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 47,
						to: 47,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 48,
						to: 48,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 49,
						to: 49,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 50,
						to: 50,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 51,
						to: 51,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 52,
						to: 52,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 53,
						to: 53,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 54,
						to: 54,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 55,
						to: 55,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 56,
						to: 56,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 57,
						to: 57,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 58,
						to: 58,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 59,
						to: 59,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 60,
						to: 60,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 61,
						to: 61,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 62,
						to: 62,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 63,
						to: 63,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 64,
						to: 64,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 65,
						to: 65,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 66,
						to: 66,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 67,
						to: 67,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 68,
						to: 68,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 69,
						to: 69,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 70,
						to: 70,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 71,
						to: 71,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 72,
						to: 72,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 73,
						to: 73,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 74,
						to: 74,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 75,
						to: 75,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 76,
						to: 76,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 77,
						to: 77,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 78,
						to: 78,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 79,
						to: 79,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 80,
						to: 80,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 81,
						to: 81,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 82,
						to: 82,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 83,
						to: 83,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 84,
						to: 84,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 85,
						to: 85,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 86,
						to: 86,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 87,
						to: 87,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 88,
						to: 88,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 89,
						to: 89,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 90,
						to: 90,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 91,
						to: 91,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 92,
						to: 92,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 93,
						to: 93,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 94,
						to: 94,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 95,
						to: 95,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 96,
						to: 96,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 97,
						to: 97,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 98,
						to: 98,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 99,
						to: 99,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 100,
						to: 104,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 211.3, ty: 53.6},
						transform: [211.3, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "digital_0_x",
				keys: [
					{
						from: 0,
						to: 9,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 10,
						to: 19,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 20,
						to: 29,
						classname: "_loading_digital_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 30,
						to: 39,
						classname: "_loading_digital_3_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 40,
						to: 49,
						classname: "_loading_digital_4_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 50,
						to: 59,
						classname: "_loading_digital_5_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 60,
						to: 69,
						classname: "_loading_digital_6_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 70,
						to: 79,
						classname: "_loading_digital_7_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 80,
						to: 89,
						classname: "_loading_digital_8_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 90,
						to: 99,
						classname: "_loading_digital_9_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 100,
						to: 104,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 85.05, ty: 53.75},
						transform: [85.05, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "digital_0_x",
				keys: [
					{
						from: 0,
						to: 99,
						classname: "_loading_digital_0_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -84, ty: 53.6},
						transform: [-84, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 100,
						to: 104,
						classname: "_loading_digital_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -84, ty: 53.6},
						transform: [-84, 53.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "digital_dots_x",
				keys: [
					{
						from: 0,
						to: 104,
						classname: "_loading_digital_dots_anima",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0.2, ty: 53.75},
						transform: [0.2, 53.75, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "txt",
				keys: [
					{
						from: 0,
						to: 99,
						classname: "_loading_loading_txt",
						instancename: "txt",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -0.05, ty: -82.15},
						transform: [-0.05, -82.15, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 100,
						to: 104,
						classname: "_loading_alarmatxt_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -0.05, ty: -82.15},
						transform: [-0.05, -82.15, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "Layer 10",
				keys: [
					{
						from: 0,
						to: 99,
						actions: function(self){self.stop();},
					},
					{
						from: 100,
						to: 104,
						actions: function(self){self.stop();},
					},
				]
			},
		]
	},
	"_loading_whity_x": {
		type: "bitmap",
		asset: "_loading_whity_x",
		scale: 1,
		position: [-55, -55],
	},
	"_loading_light_gfx": {
		type: "movieclip",
		fps: 30,
		totalFrames: 1,
		labels: {},
		layers: [
			{
				name: "l_1_x",
				keys: [
					{
						from: 0,
						to: 0,
						classname: "_loading_l_1_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 423.45, ty: 283.45},
						transform: [423.45, 283.45, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "l_2_x",
				keys: [
					{
						from: 0,
						to: 0,
						classname: "_loading_l_2_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 824, ty: 173.6},
						transform: [824, 173.6, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "l_2_x",
				keys: [
					{
						from: 0,
						to: 0,
						classname: "_loading_l_2_x",
						instancename: "",
						matrix: {a: 0.777, b: -0.088, c: -0.088, d: -0.777, tx: 870.75, ty: 508.2},
						transform: [870.75, 508.2, 0.782, 0.782, -3.029, -0.113, NaN],
						alpha: 0.83,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "gradient_x",
				keys: [
					{
						from: 0,
						to: 0,
						classname: "_loading_gradient_x",
						instancename: "",
						matrix: {a: 17.55, b: -4.039, c: 0.224, d: 0.975, tx: 570.7, ty: -20.7},
						transform: [570.7, -20.7, 18.008, 1, 0.226, -0.226, NaN],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
		]
	},
	"_loading_alarmaglow_anima": {
		type: "movieclip",
		fps: 30,
		totalFrames: 10,
		labels: {},
		layers: [
			{
				name: "Layer 1",
				keys: [
					{
						from: 0,
						to: 4,
						classname: "_loading_alarmaglow_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -33.8, ty: -0.25},
						transform: [-33.8, -0.25, 1, 1, 0, 0, 0],
						alpha: 0.48,
						visible: true,
						tween: true,
						easing: {
							all: [[0, 0], [0.55, 0], [0.55, 1], [1, 1], ],
						}
					},
					{
						from: 5,
						to: 8,
						classname: "_loading_alarmaglow_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -33.8, ty: -0.25},
						transform: [-33.8, -0.25, 1, 1, 0, 0, 0],
						alpha: 0.72,
						visible: true,
						tween: true,
						easing: {
							all: [[0, 0], [0.55, 0], [0.55, 1], [1, 1], ],
						}
					},
					{
						from: 9,
						to: 9,
						classname: "_loading_alarmaglow_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: -33.8, ty: -0.25},
						transform: [-33.8, -0.25, 1, 1, 0, 0, 0],
						alpha: 0.48,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "Capa 2",
				keys: [
					{
						from: 0,
						to: 4,
					},
					{
						from: 5,
						to: 5,
						actions: function(self){WONBATS.soundManager.play("alarm_clock");},
					},
					{
						from: 6,
						to: 9,
					},
				]
			},
		]
	},
	"_loading_buttonglow_anima": {
		type: "movieclip",
		fps: 30,
		totalFrames: 11,
		labels: {},
		layers: [
			{
				name: "Layer 1",
				keys: [
					{
						from: 0,
						to: 4,
						classname: "_loading_buttonglow_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 6.65, ty: 45.95},
						transform: [6.65, 45.95, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: true,
						easing: {
							all: [[0, 0], [0.559, 0], [0.508, 1], [1, 1], ],
						}
					},
					{
						from: 5,
						to: 9,
						classname: "_loading_buttonglow_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 6.65, ty: 45.95},
						transform: [6.65, 45.95, 1, 1, 0, 0, 0],
						alpha: 0.67,
						visible: true,
						tween: true,
						easing: {
							all: [[0, 0], [0.559, 0], [0.508, 1], [1, 1], ],
						}
					},
					{
						from: 10,
						to: 10,
						classname: "_loading_buttonglow_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 6.65, ty: 45.95},
						transform: [6.65, 45.95, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
		]
	},
	"_loading_digital_0_x": {
		type: "bitmap",
		asset: "_loading_digital_0_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_1_x": {
		type: "bitmap",
		asset: "_loading_digital_1_x",
		scale: 1,
		position: [-112.25, -127.8],
	},
	"_loading_digital_2_x": {
		type: "bitmap",
		asset: "_loading_digital_2_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_3_x": {
		type: "bitmap",
		asset: "_loading_digital_3_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_4_x": {
		type: "bitmap",
		asset: "_loading_digital_4_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_5_x": {
		type: "bitmap",
		asset: "_loading_digital_5_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_6_x": {
		type: "bitmap",
		asset: "_loading_digital_6_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_7_x": {
		type: "bitmap",
		asset: "_loading_digital_7_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_8_x": {
		type: "bitmap",
		asset: "_loading_digital_8_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_9_x": {
		type: "bitmap",
		asset: "_loading_digital_9_x",
		scale: 1,
		position: [-137.65, -127.8],
	},
	"_loading_digital_dots_anima": {
		type: "movieclip",
		fps: 30,
		totalFrames: 30,
		labels: {},
		layers: [
			{
				name: "Layer 3",
				keys: [
					{
						from: 0,
						to: 24,
						classname: "_loading_digital_dots_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 25,
						to: 29,
						classname: "_loading_digital_dots_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 0.69,
						visible: true,
						tween: false,
					},
				]
			},
		]
	},
	"_loading_loading_txt": {
		type: "movieclip",
		fps: 30,
		totalFrames: 28,
		labels: {english: {from:0, to:8}, portuguese: {from:9, to:18}, spanish: {from:19, to:27}, },
		layers: [
			{
				name: "Layer 1",
				keys: [
					{
						from: 0,
						to: 8,
						classname: "_loading_loading_engllish_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 9,
						to: 18,
						classname: "_loading_loading_portuguese_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 1.5, ty: 0},
						transform: [1.5, 0, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
					{
						from: 19,
						to: 27,
						classname: "_loading_loading_spanish_x",
						instancename: "",
						matrix: {a: 1, b: 0, c: 0, d: 1, tx: 0, ty: 0},
						transform: [0, 0, 1, 1, 0, 0, 0],
						alpha: 1,
						visible: true,
						tween: false,
					},
				]
			},
			{
				name: "Layer 2",
				keys: [
					{
						from: 0,
						to: 8,
					},
					{
						from: 9,
						to: 18,
					},
					{
						from: 19,
						to: 27,
					},
				]
			},
		]
	},
	"_loading_alarmatxt_x": {
		type: "bitmap",
		asset: "_loading_alarmatxt_x",
		scale: 1,
		position: [-174.55, -85.95],
	},
	"_loading_l_1_x": {
		type: "bitmap",
		asset: "_loading_l_1_x",
		scale: 1,
		position: [-219, -124.5],
	},
	"_loading_l_2_x": {
		type: "bitmap",
		asset: "_loading_l_2_x",
		scale: 1,
		position: [-205.5, -32.5],
	},
	"_loading_gradient_x": {
		type: "bitmap",
		asset: "_loading_gradient_x",
		scale: 1,
		position: [-46.35, -425],
	},
	"_loading_alarmaglow_x": {
		type: "bitmap",
		asset: "_loading_alarmaglow_x",
		scale: 1,
		position: [-411.2, -274.5],
	},
	"_loading_buttonglow_x": {
		type: "bitmap",
		asset: "_loading_buttonglow_x",
		scale: 1,
		position: [-110.85, -104.35],
	},
	"_loading_digital_dots_x": {
		type: "bitmap",
		asset: "_loading_digital_dots_x",
		scale: 1,
		position: [-47.65, -107.3],
	},
	"_loading_loading_engllish_x": {
		type: "bitmap",
		asset: "_loading_loading_engllish_x",
		scale: 1,
		position: [-317.05, -113.6],
	},
	"_loading_loading_portuguese_x": {
		type: "bitmap",
		asset: "_loading_loading_portuguese_x",
		scale: 1,
		position: [-322.2, -86.1],
	},
	"_loading_loading_spanish_x": {
		type: "bitmap",
		asset: "_loading_loading_spanish_x",
		scale: 1,
		position: [-345, -96.45],
	},
};
