window.switStrings =	{
	"STR_EMPTY": "",
	"STR_LOADING_PRELOAD_FONT_1": "0",
	"STR_LOADING_PRELOAD_FONT_2": "0",
	"STR_SELECTCHARACTER_ADD": "Add player",
	"STR_SELECTCHARACTER_06": "Chopper",
	"STR_SELECTCHARACTER_05": "Zeb",
	"STR_SELECTCHARACTER_04": "Hera",
	"STR_SELECTCHARACTER_03": "Sabine",
	"STR_SELECTCHARACTER_02": "Kanan",
	"STR_SELECTCHARACTER_01": "Ezra",
	"STR_SELECTCHARACTER_06_CAPTURED": "Chopper - CAPTURED",
	"STR_SELECTCHARACTER_05_CAPTURED": "Zeb – CAPTURED",
	"STR_SELECTCHARACTER_04_CAPTURED": "Hera – CAPTURED",
	"STR_SELECTCHARACTER_03_CAPTURED": "Sabine – CAPTURED",
	"STR_SELECTCHARACTER_02_CAPTURED": "Kanan – CAPTURED",
	"STR_SELECTCHARACTER_01_CAPTURED": "Ezra – CAPTURED",
	"STR_SELECTBOSS_01": "AT-DP",
	"STR_SELECTBOSS_02": "AT-AT",
	"STR_SELECTBOSS_03": "TIE FIGHTER",
	"STR_SELECTCHARACTER_P1": "P1",
	"STR_SELECTCHARACTER_P2": "P2",
	"STR_SELECTLOCATION_MISSION": "Missions",
	"STR_SELECTLOCATION_PLANET01": "Forest Planet",
	"STR_SELECTLOCATION_PLANET02": "City Planet",
	"STR_SELECTLOCATION_PLANET03": "Lava Planet",
	"STR_SKIPTUTORIAL_INFO": "End the tutorial?",
	"STR_RESET_INFO": "Reset the match?",
	"STR_TROPHIES_TROPHY_INFO01": "Complete 4 missions in multiplayer",
	"STR_TROPHIES_TROPHY_INFO02": "Use all characters",
	"STR_TROPHIES_TROPHY_INFO03": "Defeat all the Bosses",
	"STR_TROPHIES_TROPHY_INFO04": "Use all the special power ups",
	"STR_TROPHIES_TROPHY_INFO05": "Obtain 3 stars in the final mission in single player or co-op",
	"STR_TROPHIES_TROPHY_INFO06": "Finish all the missions from one planet with 3 stars in single player or co-op",
	"STR_TROPHIES_TROPHY_INFO07": "Beat all Co-op missions",
	"STR_TROPHIES_TROPHY_INFO08": "Defeat a boss without losing health",
	"STR_TROPHIES_TROPHY_INFO09": "Finish all the missions with 3 stars",
	"STR_TROPHIES_TROPHY_NAME01": "Rebel Cell ",
	"STR_TROPHIES_TROPHY_NAME02": "Ghost Crew",
	"STR_TROPHIES_TROPHY_NAME03": "Just Scrap Metal",
	"STR_TROPHIES_TROPHY_NAME04": "Weapons Specialist",
	"STR_TROPHIES_TROPHY_NAME05": "Cool Headed",
	"STR_TROPHIES_TROPHY_NAME06": "Spark of the Rebellion",
	"STR_TROPHIES_TROPHY_NAME07": "Teamwork",
	"STR_TROPHIES_TROPHY_NAME08": "Trust Your Instincts",
	"STR_TROPHIES_TROPHY_NAME09": "Special Operations",
	"STR_LEADERBOARD_SCORE_NUM": "100,000,000",
	"STR_LEADERBOARD_SCORE_NAME": "JON",
	"STR_LEADERBOARD_SCORE_PLACE": "1.",
	"STR_LEADERBOARD_SCORENUM": "234, 567, 000",
	"STR_LEADERBOARD_SCORE": "YOUR SCORE:",
	"STR_LEADERBOARD_BTN3": "ALL TIME",
	"STR_LEADERBOARD_BTN2": "THIS WEEK",
	"STR_LEADERBOARD_BTN1": "TODAY",
	"STR_SELECTMODE_VS": "VERSUS",
	"STR_SELECTMODE_COOP": "CO-OP",
	"STR_SELECTMODE_SINGLE": "SINGLE PLAYER",
	"STR_MISSION_INFO_1": "Collect all the Supply Boxes",
	"STR_MISSION_INFO_2": "Clear all the Imperial Outposts ",
	"STR_MISSION_INFO_3": "Destroy all the Imperial Machines ",
	"STR_MISSION_INFO_4": "Defeat the Boss",
	"STR_MISSION_INFO_5": "Collect all the Supply Boxes",
	"STR_MISSION_INFO_6": "Clear all the Imperial Outposts ",
	"STR_MISSION_INFO_7": "Destroy all the Imperial Machines ",
	"STR_MISSION_INFO_8": "Defeat the Boss",
	"STR_MISSION_INFO_9": "Collect all the Supply Boxes",
	"STR_MISSION_INFO_10": "Clear all the Imperial Outposts ",
	"STR_MISSION_INFO_11": "Destroy all the Imperial Machines ",
	"STR_MISSION_INFO_12": "Defeat the Boss",
	"STR_SELECT_MISION_PANEL_NAME_1": "Collection",
	"STR_SELECT_MISION_PANEL_NAME_2": "Liberation",
	"STR_SELECT_MISION_PANEL_NAME_3": "Sabotage",
	"STR_SELECT_MISION_PANEL_NAME_4": "Boss",
	"STR_SELECT_MISION_PANEL_NAME_5": "Collection",
	"STR_SELECT_MISION_PANEL_NAME_6": "Liberation",
	"STR_SELECT_MISION_PANEL_NAME_7": "Sabotage",
	"STR_SELECT_MISION_PANEL_NAME_8": "Boss",
	"STR_SELECT_MISION_PANEL_NAME_9": "Collection",
	"STR_SELECT_MISION_PANEL_NAME_10": "Liberation",
	"STR_SELECT_MISION_PANEL_NAME_11": "Sabotage",
	"STR_SELECT_MISION_PANEL_NAME_12": "Boss",
	"STR_MESSAGE_TUTORIAL_INFO": "Reach the extraction point",
	"STR_ENDLEVEL_TOTAL_NUMBER": "0",
	"STR_ENDLEVEL_TOTAL": "TOTAL",
	"STR_ENDLEVEL_TOTAL_INFO": "TOTAL SCORE",
	"STR_ENDLEVEL_NUMBER": "0",
	"STR_ENDLEVEL_INFO03": "Damage taken",
	"STR_ENDLEVEL_NUMBER": "0",
	"STR_ENDLEVEL_INFO02": "Bonus enemies",
	"STR_ENDLEVEL_NUMBER": "0",
	"STR_ENDLEVEL_INFO01": "Damage dealt",
	"STR_ENDLEVEL_PERCENT": "%",
	"STR_ENDLEVEL_PANEL_TITLE_1": "RECOVERED OBJECTS",
	"STR_ENDLEVEL_PANEL_TITLE_2": "LIBERATED AREAS",
	"STR_ENDLEVEL_PANEL_TITLE_3": "SABOTAGED UNITS",
	"STR_ENDLEVEL_PANEL_TITLE_4": "BOSS DAMAGE",
	"STR_ENDLEVEL_PANEL_TITLE_TIME": "TIME TAKEN",
	"STR_ENDLEVEL_PANEL_INFO_1": "7/7",
	"STR_ENDLEVEL_PANEL_INFO_2": "4:23",
	"STR_HELP_PAGE_1": "Press the UP arrow key to jump",
	"STR_HELP_PAGE_2": "Press the UP arrow key twice to double jump",
	"STR_HELP_PAGE_3": "Press the SPACE BAR to attack",
	"STR_HELP_PAGE_4": "Press X key to use the special attack",
	"STR_HELP_PAGE_5_M": "Force Push - Pick up power-up to use Force abilities ",
	"STR_HELP_PAGE_5_R": "Explosive Shot - Pick up power-up to shoot explosive projectiles ",
	"STR_HELP_PAGE_6_M": "Deflect Shots - Pick up power-up to triple deflect blasts ",
	"STR_HELP_PAGE_6_R": "Multi-Shot - Pick up power-up to shoot 3 blaster bolts ",
	"STR_HELP_PAGE_7": "Arcade token - Spend it in the Star Wars Arcade",
	"STR_HELP_PAGE_1_MOBILE": "Press JUMP button to jump",
	"STR_HELP_PAGE_2_MOBILE": "Press the JUMP button twice to double jump",
	"STR_HELP_PAGE_3_MOBILE": "Press the ACTION button to attack",
	"STR_HELP_PAGE_4_MOBILE": "Press SPECIAL button to use the special attack",
	"STR_HELP_PAGE_5_M_MOBILE": "Force Push - Pick up power-up to use Force abilities ",
	"STR_HELP_PAGE_5_R_MOBILE": "Explosive Shot - Pick up power-up to shoot explosive projectiles ",
	"STR_HELP_PAGE_6_M_MOBILE": "Deflect Shots - Pick up power-up to triple deflect blasts ",
	"STR_HELP_PAGE_6_R_MOBILE": "Multi-Shot - Pick up power-up to shoot 3 blaster bolts ",
	"STR_HELP_PAGE_7_MOBILE": "Arcade token - Spend it in the Star Wars Arcade",
	"STR_QUIT_INFO": "Are you sure?",
	"STR_QUIT_ARCADE": "Do you want to visit the Star Wars Arcade? ",
	"STR_DIALOGUE_NAME01": "Mission Update",
	"STR_DIALOGUE_NAME02": "Mission Objective",
	"STR_DIALOGUE_INFO01": "Return to the Extraction Point ",
	"STR_DIALOGUE_INFO02": "Destroy the main Imperial Antenna.",
	"STR_DIALOGUE_INFO03": "Destroy all the Imperial Machines first. ",
	"STR_POWERUP_NAME01": "FORCE PUSH",
	"STR_POWERUP_NAME02": "DEFLECT SHOTS",
	"STR_POWERUP_NAME03": "EXPLOSIVE SHOT",
	"STR_POWERUP_NAME04": "MULTI-SHOT",
	"STR_POWERUP_NAME05": "ENERGY SHIELD",
	"STR_MESSAGE_PLAYER_1": "PLAYER 1",
	"STR_MESSAGE_PLAYER_2": "PLAYER 2",
	"STR_TUTORIAL_SELECT1": "Tap to select",
	"STR_TUTORIAL_SELECT2": "Tap to confirm",
	"STR_LOADING_PERCENT": "#N#",
	"STR_WARNING_MESSAGE": "Take out enemies to liberate civilians",
	"STR_TOKEN_INFO01": "Spend it in the Star Wars Arcade",
	"STR_LETTER_1": "A",
	"STR_LETTER_2": "B",
	"STR_LETTER_3": "C",
	"STR_LETTER_4": "D",
	"STR_LETTER_5": "E",
	"STR_LETTER_6": "F",
	"STR_LETTER_7": "G",
	"STR_LETTER_8": "H",
	"STR_LETTER_9": "I",
	"STR_LETTER_10": "J",
	"STR_LETTER_11": "K",
	"STR_LETTER_12": "L",
	"STR_LETTER_13": "M",
	"STR_LETTER_14": "N",
	"STR_LETTER_15": "O",
	"STR_LETTER_16": "P",
	"STR_LETTER_17": "Q",
	"STR_LETTER_18": "R",
	"STR_LETTER_19": "S",
	"STR_LETTER_20": "T",
	"STR_LETTER_21": "U",
	"STR_LETTER_22": "V",
	"STR_LETTER_23": "W",
	"STR_LETTER_24": "X",
	"STR_LETTER_25": "Y",
	"STR_LETTER_26": "Z",
	"STR_SAVENAME": "SAVE NAME"
};
